using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BepInEx.AutoPlugin;

[Generator]
public sealed class AutoPluginGenerator : IIncrementalGenerator
{
    const string BepInAutoPluginAttr = "BepInEx.BepInAutoPluginAttribute";
    const string PatcherAutoPluginAttr =
        "BepInEx.Preloader.Core.Patching.PatcherAutoPluginAttribute";
    const string BepInPluginAttr = "BepInEx.BepInPlugin";
    const string PatcherPluginInfoAttr = "BepInEx.Preloader.Core.Patching.PatcherPluginInfo";
    const string AttributeCode = """
        // <auto-generated />
        #nullable enable
        namespace BepInEx
        {
            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            [System.Diagnostics.Conditional("CodeGeneration")]
            internal sealed class BepInAutoPluginAttribute : System.Attribute
            {
                public BepInAutoPluginAttribute(string? id = null, string? name = null, string? version = null) {}
            }
        }

        namespace BepInEx.Preloader.Core.Patching
        {
            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            [System.Diagnostics.Conditional("CodeGeneration")]
            internal sealed class PatcherAutoPluginAttribute : System.Attribute
            {
                public PatcherAutoPluginAttribute(string? id = null, string? name = null, string? version = null) {}
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("BepInAutoPluginAttribute.g.cs", AttributeCode);
        });

        var references = context.CompilationProvider.Select(
            (compilation, _) => compilation.ReferencedAssemblyNames
        );

        IncrementalValueProvider<bool> isBepInEx5 = references.Select(
            (refs, _) =>
            {
                var bepInEx = refs.FirstOrDefault(r => r.Name.Equals("BepInEx"));

                // BepInEx 5 doesn't support plugins having version pre-release or build metadata
                // such as 1.0.0-beta or 1.0.0+97ec53d20958b88581680d4d3c15ba59a8900ed5
                bool isBepInEx5 = bepInEx is not null && bepInEx.Version.Major == 5;

                return isBepInEx5;
            }
        );

        IncrementalValueProvider<PluginProps> pluginProps = context
            .AnalyzerConfigOptionsProvider.Combine(isBepInEx5)
            .Select(
                static (info, _) =>
                {
                    var (options, isBepInEx5) = info;
                    options.GlobalOptions.TryGetValue(
                        "build_property.AssemblyName",
                        out var assName
                    );
                    options.GlobalOptions.TryGetValue(
                        "build_property.Product",
                        out var productName
                    );
                    options.GlobalOptions.TryGetValue("build_property.Version", out var version);
                    options.GlobalOptions.TryGetValue(
                        "build_property.BepInAutoPluginStripBuildMetadata",
                        out var stripMetadata
                    );

                    // Afaik these should always be set.
                    assName ??= "unknown";
                    productName ??= "unknown";
                    version ??= "0.0.0.0";

                    bool isStripMetadata =
                        stripMetadata?.Equals("true", StringComparison.InvariantCultureIgnoreCase)
                        ?? false;

                    if (isBepInEx5)
                    {
                        version = version.Split('-', '+')[0];
                    }
                    else if (isStripMetadata)
                    {
                        version = version.Split('+')[0];
                    }

                    return new PluginProps(assName, productName, version);
                }
            );

        IncrementalValuesProvider<PluginClass> classesWithBepInAutoPlugin = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                BepInAutoPluginAttr,
                static (s, _) => s is ClassDeclarationSyntax,
                static (ctx, _) =>
                    ToPluginClassWithAttribute(ctx, BepInPluginAttr, BepInAutoPluginAttr)
            )
            .Where(x => x is not null)!;

        context.RegisterSourceOutput(classesWithBepInAutoPlugin.Combine(pluginProps), WriteClass);

        IncrementalValuesProvider<PluginClass> classesWithPatcherAutoPlugin = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                PatcherAutoPluginAttr,
                static (s, _) => s is ClassDeclarationSyntax,
                static (ctx, _) =>
                    ToPluginClassWithAttribute(ctx, PatcherPluginInfoAttr, PatcherAutoPluginAttr)
            )
            .Where(x => x is not null)!;

        context.RegisterSourceOutput(classesWithPatcherAutoPlugin.Combine(pluginProps), WriteClass);
    }

    static PluginClass? ToPluginClassWithAttribute(
        GeneratorAttributeSyntaxContext ctx,
        string attributeFqn,
        string autoAttributeFqn
    )
    {
        var target = ctx.TargetNode;
        if (ctx.SemanticModel.GetDeclaredSymbol(target) is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var attr = ctx.Attributes.FirstOrDefault(att =>
            att.AttributeClass?.ToDisplayString() == autoAttributeFqn
        );

        if (attr is null || attr.ConstructorArguments.Length != 3)
            return null;

        var id = attr.ConstructorArguments[0].Value as string;
        var name = attr.ConstructorArguments[1].Value as string;
        var version = attr.ConstructorArguments[2].Value as string;

        var ns = typeSymbol.ContainingNamespace;
        var containingNamespace = ns.IsGlobalNamespace ? null : ns.ToDisplayString();

        return new PluginClass(
            containingNamespace,
            typeSymbol.Name,
            attributeFqn,
            new PluginProps(id, name, version)
        );
    }

    private void WriteClass(
        SourceProductionContext context,
        (PluginClass plugin, PluginProps pluginProps) source
    )
    {
        try
        {
            var (plugin, props) = source;

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated />");

            string? id = plugin.Overrides.Id ?? props.Id;
            string? name = plugin.Overrides.Name ?? props.Name;
            string? version = plugin.Overrides.Version ?? props.Version;
            string pluginClass = plugin.ClassName;

            if (plugin.Namespace is not null)
            {
                sb.Append("namespace ").AppendLine(plugin.Namespace).AppendLine("{");
            }

            var classStr = $$"""
                    [{{plugin.BepInAttribute}}({{pluginClass}}.Id, "{{name}}", "{{version}}")]
                    partial class {{pluginClass}}
                    {
                        /// <summary>
                        /// The Id of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public const string Id = "{{id}}";

                        /// <summary>
                        /// Gets the name of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public static string Name => "{{name}}";

                        /// <summary>
                        /// Gets the version of <see cref="{{pluginClass}}"/>.
                        /// </summary>
                        public static string Version => "{{version}}";
                    }
                """;

            sb.AppendLine(classStr);

            if (plugin.Namespace is not null)
            {
                sb.AppendLine("}");
            }

            var fileName = $"{plugin.Namespace}.{plugin.ClassName}.AutoPlugin.g.cs";
            context.AddSource(fileName, sb.ToString());
        }
        catch (Exception ex)
        {
            throw new Exception(ex.ToString().Replace('\n', ','));
        }
    }

    public sealed record PluginClass(
        string? Namespace,
        string ClassName,
        string BepInAttribute,
        PluginProps Overrides
    );

    public sealed record PluginProps(string? Id, string? Name, string? Version);
}
